Repository numpy/numpy.org, pull requests merged in 2020-03, with the labels that each got.

#176 Remove Hindi translations.
  config.yaml
  content/hi/about.md
  content/hi/arraycomputing.md
  content/hi/community.md
  content/hi/contribute.md
  content/hi/install.md
  content/hi/learning.md
Labels: translations

#177 New Crowdin translations
  content/nl/about.md
Labels: translations

#166 Travis re-setup - removed the docker
  .scripts/build.sh
  .scripts/deploy.sh
  .scripts/install.sh
  .travis.yml
  Dockerfile
  README.md
Labels: deployment

#178 Finish content on Get Help and Community pages.
  config.yaml
  content/en/community.md
  content/en/gethelp.md
  layouts/partials/single/content.html
Labels: content

#170 Cross platform and browser testing for Hugo generated pages and WCAG AA compliance
  config.yaml
  layouts/partials/data-science.html
  layouts/partials/footer.html
  layouts/partials/hero-body.html
  layouts/partials/machine-learning.html
  layouts/partials/navbar.html
  layouts/partials/scientific-domains.html
  layouts/partials/section3.html
  layouts/partials/visualization.html
  static/css/section3.css
Labels: maintenance

#183 Change styling for high-resolution screens
  static/css/section2.css
  static/css/section3.css
Labels: design

#188 adds mailchimp integration to footer email form
  layouts/partials/footer.html
  static/css/styles.css
  static/js/app.js
Labels: design, enhancement

#179 Add a full install guide
  content/en/install.md
  content/en/installing-python-and-numpy-guide.md
  static/images/content_images/python_environment_xkcd.png
Labels: content

#191 Fix disappeared blockquotes in case studies.
  config.yaml
Labels: maintenance

#192 Fixes hugo loading error with updated theme
  content/en/installing-python-and-numpy-guide.md
Labels: defect

#189 Make "Get started" button link work
  config.yaml
  layouts/partials/hero-body.html
Labels: design

#187 additional aria-labels
  layouts/partials/footer.html
Labels: accessibility

#195 Improve the content and layout of the "Key Features" tiles.
  config.yaml
  static/css/section2.css
Labels: content, design

#194 Add content for the lesson displayed when the shell is active.
  layouts/partials/shell-content.html
  layouts/partials/shell-lesson.html
  static/css/shell.css
Labels: content

#199 Reorganize the links in the footer
  config.yaml
Labels: maintenance

#200 Fix the link to NumPy documentation
  config.yaml
Labels: maintenance

#197 Web accessibility - Contrast ratio for WCGA AA
  config.yaml
  layouts/partials/footer.html
  static/css/section2.css
  static/css/tabs.css
Labels: accessibility

#206 Fix two typos in the install guide
  content/en/installing-python-and-numpy-guide.md
Labels: maintenance

#207 Minor text edits on multiple pages
  content/en/about.md
  content/en/arraycomputing.md
  content/en/contribute.md
  content/en/learn.md
  content/en/report-handling-manual.md
  layouts/partials/array-libraries.html
  layouts/partials/data-science.html
Labels: content

#210 adds list.html to quiet hugo server warning.
  layouts/_default/list.html
Labels: maintenance
