Repository numpy/numpy.org, pull requests merged in 2020-07, with the labels that each got.

#330 Update NumPy logos
  static/images/favicon.png
  static/images/logos/numpy.svg
  static/images/logos/numpy_logo.svg
Labels: design

#324 Addresses #315: DeepLabCut Case Study in collaboration with Alexander…
  config.yaml
  content/en/case-studies/deeplabcut-dnn.md
  static/images/content_images/case_studies/deeplabcut.png
  static/images/content_images/cs/deeplabcut-toolkit-steps.png
  static/images/content_images/cs/deeplabcut-workflow.png
  static/images/content_images/cs/mice-hand.gif
  static/images/content_images/cs/numpy_dlc_benefits.png
  static/images/content_images/cs/pose-estimation.png
  static/images/content_images/cs/race-horse.gif
Labels: New Addition, content

#332 Add news entries on 1.19.0, the new logo and the survey
  config.yaml
  content/en/news.md
Labels: content

#334 Update crowdin.yml for case studies being in a sub-folder
  crowdin.yml
Labels: translations

#336 Remove Dutch translation
  config.yaml
  content/nl/about.md
  content/nl/arraycomputing.md
  content/nl/community.md
  content/nl/contribute.md
  content/nl/install.md
  content/nl/learning.md
Labels: translations

#333 Survey end date will be dropped, so remove a mention of that
  config.yaml
  content/en/news.md
Labels: content, maintenance

#338 DOC: Add color swatches to NumPy palette in README
  README.md
  static/images/content_images/swatch_013243_warm_black.png
  static/images/content_images/swatch_4D77CF_han_blue.png
  static/images/content_images/swatch_4DABCF_maximum_blue.png
  static/images/content_images/swatch_6C7A89_aurometalsaurus.png
  static/images/content_images/swatch_EEEEEE_isabelline.png
  static/images/content_images/swatch_FFC553_mustard.png
  static/images/content_images/swatch_FFFFFF_white.png
Labels: maintenance

#276 Slightly increase font size of titles of tabs on front page
  static/css/tabs.css
Labels: design

#341 Update the news article about the CZI grant
  content/en/news.md
Labels: content
