Repository numpy/numpy.org, pull requests merged in 2020-05, with the labels that each got.

#196 DOC: EHT Case Study Suggestions
  content/en/case-studies/blackhole-image.md
Labels: content

#226 Fixes minor typos and grammar ref pull request 174
  content/en/case-studies/cricket-analytics.md
Labels: content, enhancement

#224 Fixes #gh-223 color palette update as per #gh-33 in infographics for …
  layouts/partials/data-science.html
  static/images/content_images/data-science.png
  static/images/content_images/ds-landscape.png
Labels: design

#218 Enhanced scripts to generate numpy dependency graph for various pkg
  content/en/case-studies/gw-discov.md
  scripts/fetch-ehtim.sh
  scripts/numpy-ehtim-dep-graph.sh
  scripts/pkgdepchart/README.md
  scripts/pkgdepchart/cleanup-numpydeppkg.sh
  scripts/pkgdepchart/fetch-numpydeppkg.sh
  scripts/pkgdepchart/gen-numpy-dep-graph.sh
  scripts/pkgdepchart/redraw-numpy-dep-charts.sh
  static/images/content_images/cs/PyCBC-numpy-dep-graph.png
  static/images/content_images/cs/gwpy-numpy-dep-graph.png
Labels: content, enhancement

#225 DOC: update members of the CoC committee
  content/en/code-of-conduct.md
Labels: maintenance

#228 Moves shell below key features
  config.yaml
  layouts/index.html
  layouts/partials/css.html
  layouts/partials/hero-body.html
  layouts/partials/hero.html
  layouts/partials/keyfeatures.html
  layouts/partials/news.html
  layouts/partials/section2.html
  layouts/partials/shell.html
  static/css/keyfeatures.css
  static/css/news.css
  static/css/section2.css
  static/css/styles.css
Labels: design

#230 Add a News page
  config.yaml
  content/en/news.md
  layouts/partials/news.html
  static/css/news.css
Labels: content

#241 DOC: Fix Hugo install instructions in README (issue #231)
  README.md
Labels: maintenance

#245 Rewording for gravitational waves caption
  config.yaml
Labels: content

#243 Fix links
  content/en/case-studies/cricket-analytics.md
  content/en/community.md
  content/en/contribute.md
  content/en/learn.md
  static/gallery/team.html
Labels: maintenance

#251 Make example in interactive shell copy-pastable
  layouts/partials/shell-lesson.html
Labels: content

#242 DOC: Emphasize NumPy in Ecosystem openers
  layouts/partials/array-libraries.html
  layouts/partials/data-science.html
  layouts/partials/machine-learning.html
  layouts/partials/scientific-domains.html
  layouts/partials/visualization.html
Labels: content

#257 Hide the "array computing" page in the navbar
  config.yaml
Labels: content

#255 Bug/mobile css
  config.yaml
  layouts/partials/keyfeatures.html
  layouts/partials/navbar.html
  static/css/content.css
  static/css/keyfeatures.css
  static/css/news.css
  static/css/section3.css
  static/css/shell.css
  static/css/styles.css
Labels: design

#260 DOC: Tighten ecosystem->array libraries
  layouts/partials/array-libraries.html
Labels: content

#264 Remove sentence about logo under "Graphic design" on Contributing page
  content/en/contribute.md
Labels: content

#253 DOC: Make 'dev issues' more prominent in help page
  content/en/gethelp.md
Labels: content

#270 Update numpy version in interactive shell; fix example width
  layouts/partials/javascript.html
  static/css/shell.css
Labels: content, design, maintenance

#259 Updates colors to Warm Black
  layouts/partials/footer.html
  static/css/styles.css
Labels: design

#273 removes padding from p element in footer email
  static/css/styles.css
Labels: design

#272 Update content of Data Science tab
  layouts/partials/data-science.html
Labels: content

#268 Update array libraries tab content
  layouts/partials/array-libraries.html
  static/images/content_images/arlib/cuDF.png
  static/images/content_images/arlib/jax_logo_250px.png
  static/images/content_images/arlib/mxnet_logo.png
  static/images/content_images/arlib/pytorch-logo-dark.svg
  static/images/content_images/arlib/tensorflow-logo.svg
  static/images/content_images/arlib/xframes.png
Labels: content

#258 DOC: Integrate Learn and Documentation pages
  content/en/learn.md
Labels: content

#277 Final review of the content
  content/en/about.md
  content/en/arraycomputing.md
  content/en/case-studies/blackhole-image.md
  content/en/case-studies/cricket-analytics.md
  content/en/case-studies/gw-discov.md
  content/en/citing-numpy.md
  content/en/code-of-conduct.md
  content/en/installing-python-and-numpy-guide.md
  content/en/learn.md
  content/en/news.md
  content/en/press-kit.md
  static/gallery/team.html
Labels: content

#275 Switch order of tabs - "scientific domains" first
  layouts/partials/tabs.html
Labels: design

#274 Another edit to graphic design request for contributions
  content/en/contribute.md
Labels: content

#281 Fix punctuation
  config.yaml
Labels: content, maintenance

#279 Make "Documentation" link to numpy.org/doc/stable
  config.yaml
  content/en/learn.md
  layouts/partials/shell-content.html
Labels: maintenance

#280 Move the separate Python and NumPy install guide into main install page
  content/en/install.md
  content/en/installing-python-and-numpy-guide.md
Labels: navigation

#284 Some last minor tweaks to textual things
  content/en/learn.md
  layouts/partials/data-science.html
Labels: maintenance

#286 DOC: Drop unneeded word from Ecosystem->Data Science
  layouts/partials/data-science.html
Labels: content, maintenance

#287 Minor tweak between title and text in news bar
  static/css/news.css
Labels: design

#288 Make the Get Started button point to the Install page
  config.yaml
Labels: navigation

#291 Update the meta description of the site
  config.yaml
Labels: maintenance

#299 Address the issues from gh-295
  layouts/partials/scientific-domains.html
Labels: maintenance

#304 Improve "scientific domains" ecosystem figure.
  layouts/partials/scientific-domains.html
Labels: content

#305 Switch sd9.png and sd10.png
  layouts/partials/scientific-domains.html
Labels: content

#307 Make SymPy links point to its home page rather than its GitHub repo
  layouts/partials/scientific-domains.html
Labels: maintenance

#310 Bug/clickable case studies
  config.yaml
  layouts/index.html
  layouts/partials/casestudies.html
  layouts/partials/css.html
  layouts/partials/section3.html
  static/css/casestudies.css
Labels: maintenance

#311 adds frontmatter alias for conduct.html from old numpy.org
  content/en/code-of-conduct.md
Labels: maintenance
