Repository numpy/numpy.org, pull requests merged in 2020-01, with the labels that each got.

#115 Create team.md
  content/en/about.md
  content/en/team.md
Labels: content

#109 Add new content
  content/en/citing-numpy.md
  content/en/code-of-conduct.md
  content/en/learn.md
  content/en/privacy.md
  content/en/terms.md
  layouts/partials/footer.html
  static/css/styles.css
Labels: content

#119 Update community.md
  content/en/community.md
Labels: content

#124 travis setup config file added
  .github/actions/deploy-action/action.yml
  .github/pull_request_template.md
  .github/workflows/main.yml
  .scripts/deploy.sh
  .travis.yml
Labels: deployment

#133 Update link to Numeric manual, remove pdf from repo
  www/_static/numeric-manual.pdf
  www/old_array_packages.rst
Labels: maintenance

#140 Fixes link for license information using github license file Ref #gh_138
  config.yaml
  layouts/partials/section2.html
Labels: content

#139 Feature/83 performance
  layouts/partials/css.html
  layouts/partials/hero-body.html
  layouts/partials/javascript.html
  static/css/shell.css
  static/css/styles.css
  static/js/app.js
Labels: design, enhancement

#125 Remove "general purpose" tab
  layouts/partials/tabs.html
Labels: content

#126 Update the About Us page
  content/en/about.md
  static/images/logos/CZI.svg
  static/images/logos/NumFOCUS_sponsored_project_logo.svg
  static/images/logos/berkeley-color.svg
  static/images/logos/moore.svg
  static/images/logos/quansight.svg
  static/images/logos/sloan.svg
  static/images/logos/tidelift.png
Labels: content, design

#127 Finish Contribute page
  content/en/contribute.md
Labels: content

#113 Create report-handling-manual.md
  content/en/code-of-conduct.md
  content/en/report-handling-manual.md
  layouts/partials/footer.html
  static/css/styles.css
Labels: content

#149 Fix the link to the new Twitter account
  content/en/community.md
Labels: maintenance

#137 Create gethelp.md and history.md
  content/en/gethelp.md
  content/en/history.md
Labels: content

#150 Removed loading animations
  layouts/_default/baseof.html
  layouts/_default/single.html
Labels: design, maintenance

#161 Recover script to create the EHT imaging dependency graph
  scripts/fetch-ehtim.sh
  scripts/numpy-ehtim-dep-graph.sh
Labels: maintenance
