Repository numpy/numpy.org, pull requests merged in 2020-08, with the labels that each got.

#348 Remove Surge and TravisCI preview deployment that wasn't working.
  .github/pull_request_template.md
  .scripts/build.sh
  .scripts/deploy.sh
  .scripts/install.sh
  .travis.yml
  Dockerfile
  README.md
Labels: maintenance

#353 deploy via gh-pages
  Makefile
Labels: deployment

#356 Update Prof Mathis affiliation in DeepLabCut case study
  content/en/case-studies/deeplabcut-dnn.md
Labels: content, enhancement

#355 Update title bar after closing of the Survey
  config.yaml
Labels: content, maintenance

#343 Homepage - remove the excess whitespace
  static/css/keyfeatures.css
Labels: design
