Repository numpy/numpy.org, pull requests merged in 2021-02, with the labels that each got.

#390 Update Github Action
  .github/workflows/gh-pages.yml
Labels: deployment

#393 Fix typo: Numerical -> Numeric
  content/en/about.md
Labels: maintenance

#394 Ensure the new GitHub Action adds CNAME
  .github/workflows/gh-pages.yml
Labels: deployment

#396 Update .content-container
  static/css/content.css
Labels: design, maintenance

#402 Update Numpy Docs link in learn.md
  content/en/learn.md
Labels: maintenance
