Repository numpy/numpy.org, pull requests merged in 2021-04, with the labels that each got.

#403 Replace icons in Scientific Domains tab
  layouts/partials/scientific-domains.html
  static/images/content_images/sc_dom_img/GIS.svg
  static/images/content_images/sc_dom_img/astronomy_processes.svg
  static/images/content_images/sc_dom_img/bayesian_inference.svg
  static/images/content_images/sc_dom_img/bioinformatics.svg
  static/images/content_images/sc_dom_img/chemistry.svg
  static/images/content_images/sc_dom_img/cognitive_psychology.svg
  static/images/content_images/sc_dom_img/geoscience.svg
  static/images/content_images/sc_dom_img/image_processing.svg
  static/images/content_images/sc_dom_img/mathematical_analysis.svg
  static/images/content_images/sc_dom_img/quantum_computing.svg
  static/images/content_images/sc_dom_img/robotics.svg
  static/images/content_images/sc_dom_img/sd1.png
  static/images/content_images/sc_dom_img/sd10.png
  static/images/content_images/sc_dom_img/sd11.png
  static/images/content_images/sc_dom_img/sd12.png
  static/images/content_images/sc_dom_img/sd13.png
  static/images/content_images/sc_dom_img/sd14.png
  static/images/content_images/sc_dom_img/sd15.png
  static/images/content_images/sc_dom_img/sd2.png
  static/images/content_images/sc_dom_img/sd3.png
  static/images/content_images/sc_dom_img/sd33.png
  static/images/content_images/sc_dom_img/sd4.png
  static/images/content_images/sc_dom_img/sd6.svg
  static/images/content_images/sc_dom_img/sd7.png
  static/images/content_images/sc_dom_img/sd8.png
  static/images/content_images/sc_dom_img/sd9.png
  static/images/content_images/sc_dom_img/signal_processing.svg
  static/images/content_images/sc_dom_img/statistical_computing.svg
Labels: design, maintenance

#412 Add two more projects to Chemistry in scientific domains tab
  layouts/partials/scientific-domains.html
Labels: content

#414 Update steering council members
  content/en/about.md
Labels: content, maintenance

#410 Update learn.md
  content/en/learn.md
Labels: content

#413 Integrate Japanese and Brazilian translations
  .github/workflows/gh-pages.yml
  .gitignore
  Makefile
  README.md
  config.yaml
  config.yaml.in
  content/en/config.yaml
  content/ja/404.md
  content/ja/about.md
  content/ja/arraycomputing.md
  content/ja/case-studies/blackhole-image.md
  content/ja/case-studies/cricket-analytics.md
  content/ja/case-studies/deeplabcut-dnn.md
  content/ja/case-studies/gw-discov.md
  content/ja/citing-numpy.md
  content/ja/code-of-conduct.md
  content/ja/community.md
  content/ja/config.yaml
  content/ja/contribute.md
  content/ja/diversity_sep2020.md
  content/ja/gethelp.md
  content/ja/history.md
  content/ja/install.md
  content/ja/learn.md
  content/ja/news.md
  content/ja/press-kit.md
  content/ja/privacy.md
  content/ja/report-handling-manual.md
  content/ja/terms.md
  content/pt/404.md
  content/pt/about.md
  content/pt/arraycomputing.md
  content/pt/case-studies/blackhole-image.md
  content/pt/case-studies/cricket-analytics.md
  content/pt/case-studies/deeplabcut-dnn.md
  content/pt/case-studies/gw-discov.md
  content/pt/citing-numpy.md
  content/pt/code-of-conduct.md
  content/pt/community.md
  content/pt/config.yaml
  content/pt/contribute.md
  content/pt/diversity_sep2020.md
  content/pt/gethelp.md
  content/pt/history.md
  content/pt/install.md
  content/pt/learn.md
  content/pt/news.md
  content/pt/press-kit.md
  content/pt/privacy.md
  content/pt/report-handling-manual.md
  content/pt/terms.md
  crowdin.yml
  gen_config.py
  layouts/partials/array-libraries.html
  layouts/partials/data-science.html
  layouts/partials/machine-learning.html
  layouts/partials/navbar-clone.html
  layouts/partials/navbar.html
  layouts/partials/scientific-domains.html
  layouts/partials/visualization.html
Labels: translations

#421 Update citing-numpy.md
  content/en/citing-numpy.md
Labels: content, maintenance

#415 Update config.yaml for Japanese page
  config.yaml
  content/ja/config.yaml
Labels: translations

#418 Added translation of main page to Portuguese (Brazilian)
  config.yaml
  content/pt/config.yaml
Labels: translations

#419 Added link to numpy-tutorials
  content/en/learn.md
Labels: content, maintenance

#427 Remove generated config.toml, show translations in preview
  config.yaml
  gen_config.py
  netlify.toml
Labels: deployment, translations

#422 Upgrade Hugo from 0.74 to 0.82
  .github/workflows/gh-pages.yml
Labels: deployment

#428 Update Japanese language name in dropdown selector
  config.yaml.in
  content/ja/config.yaml
Labels: translations

#424 fix some typos, link layout, and translations in Japanese `Install` page.
  content/ja/install.md
Labels: translations

#430 Fix intra-site links for translations, and remove duplicates of 2020 diversity statement
  content/ja/community.md
  content/ja/contribute.md
  content/ja/diversity_sep2020.md
  content/ja/learn.md
  content/pt/community.md
  content/pt/contribute.md
  content/pt/diversity_sep2020.md
  content/pt/learn.md
Labels: maintenance, translations
