Repository numpy/numpy.org, pull requests merged in 2021-01, with the labels that each got.

#377 Create Github Actions
  .github/workflows/gh-pages.yml
Labels: deployment

#376 Add overflow: auto to .content-container to fix install page
  static/css/content.css
Labels: design, maintenance

#378 Fix Font Awesome Icons
  content/en/learn.md
  layouts/partials/footer.html
  layouts/partials/javascript.html
  layouts/shortcodes/numfocus.html
  static/css/styles.css
Labels: maintenance

#379 Add CNAME during deployment to gh-pages
  .github/workflows/gh-pages.yml
Labels: deployment

#380 A small tweak to the About page (mostly to test deployment)
  content/en/about.md
Labels: maintenance

#381 Trivial commit to redeploy
  content/en/about.md
Labels: deployment

#382 Revert "Add CNAME during deployment to gh-pages"
  .github/workflows/gh-pages.yml
Labels: deployment

#389 Add news item for NumPy 1.20.0 release
  config.yaml
  content/en/news.md
Labels: content
