Repository numpy/numpy.org, pull requests merged in 2021-03, with the labels that each got.

#405 Specify RGB values in the docs regarding the NumPy website color palette
  README.md
Labels: design, maintenance

#407 Add a link to numpy.org/citing-numpy/ in the footer
  config.yaml
Labels: content, maintenance

#408 Update crowdin.yml files to ignore, yml format change
  crowdin.yml
Labels: translations

#409 Minor textual tweak to the Install page content
  content/en/install.md
Labels: maintenance
